default_platform(:android)

platform :android do

    def aab_path
      "../android/app/build/outputs/bundle/release/app-release.aab"
    end
  ########################################
  # Common helper
  ########################################
  def upload_closed(track:, version:, aab_path:)
    upload_to_play_store(
      track: track,
      aab: aab_path,
      release_status: "completed",
      version_name: version
          )
  end

########################################
# Production – full rollout
########################################
desc "Upload AAB to Production (100%)"
lane :production do
  upload_to_play_store(
    track: "production",
    aab: "D:/AndroidProjects/androidircx/android/app/build/outputs/bundle/release/app-release.aab",
    # aab: aab_path,
    release_status: "completed"
  )
end

end
